
services:
  postgres:
    container_name: psicologo
    image: postgres:latest
    environment:
      POSTGRES_DB: psicologo
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: igor
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres-db-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-psicologo
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  postgres-db-network:
    driver: bridge