
services:
  postgres:
    container_name: guinchae_db
    image: postgres:latest
    environment:
      POSTGRES_DB: psicologo
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-psicologo
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"
volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  keycloak:
    driver: local

networks:
  postgres-db-network:
    driver: bridge